config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :userprofile, only: [:index]
  resources :cwavetests, only: [:index, :create, :new]
  resources :user_accounts, only: [:index], path: "/mypage" do
    collection do
      get :logout
    end
  end
  resources :card_registrations, only: [:index, :new], path: "/mypage/card"
  resources :signup, only: [:new, :create] do
    collection do
      get :step1
      get :step2
      get :step3
      get :step4
    end
  end
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'js' }
      get 'get_category_grandchildren', defaults: { format: 'js' }
    end
    resources :purchases, only: [:index] do
      collection do
        post :pay
      end
    end
  end
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def index
  end

  def top_page
  end

  def logout
  end
end

app/views/user_accounts/_mypage_body.html.haml
.main__inner__body
  .main__inner__body__user-icon
    = link_to "#", class: "user-icon__link" do
      .user-icon__link__image
        = image_tag 'mypage/boy_01.png', alt: 'user_icon', height: '60', width: '60'
      %h2.user-icon__link__nickname ユーザーニックネーム
      %ul.user-icon__link__statistics
        %li.user-icon__link__statistics__rate
          評価
          %span 10
        %li.user-icon__link__statistics__prod-count
          出品数
          %span 5
  .main__inner__body__notification
    %ul.main__inner__body__notification__tabs
      %li#notice-tab.main__inner__body__notification__tabs__title.active
        = link_to "お知らせ", "#"
      %li#todo-tab.main__inner__body__notification__tabs__title
        = link_to "やることリスト", "#"
    %ul.main__inner__body__notification__messages
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 事務局から個別メッセージ
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 事務局から個別メッセージ
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 事務局から個別メッセージ
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 事務局から個別メッセージ
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 事務局から個別メッセージ
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item--show-all
        = link_to "一覧をみる", "#"
    %ul.main__inner__body__notification__alerts
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 購入した商品のお支払いをしてください
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
      %li.main__inner__body__notification__messages__item
        = link_to "#", class: "messages__item" do
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
          .messages__item__content
            .messages__item__content__text 出品した商品を発送してください
            .messages__item__content__date
              = icon("far", "clock")
              %span ２日前
          .messages__item__arrow
            = icon("fas", "chevron-right")
  .main__inner__body__purchase-history
    %h2.main__inner__body__purchase-history__title 購入した商品
    %ul.main__inner__body__purchase-history__tabs
      %li#current-transaction-tab.main__inner__body__purchase-history__tabs__title.active
        = link_to "取引中", "#"
      %li#previous-transaction-tab.main__inner__body__purchase-history__tabs__title
        = link_to "過去の取引", "#"
    .main__inner__body__purchase-history__content
      %ul.main__inner__body__purchase-history__content__current
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 山田さんから自転車を購入（取引中）
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 田中さんからスマホケースを購入（取引中）
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 山田さんから自転車佐藤さんからmacbookを購入（取引中）を購入（取引中）
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")
      %ul.main__inner__body__purchase-history__content__previous
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 山田さんから自転車を購入
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 田中さんからスマホケースを購入
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")
        %li.main__inner__body__notification__messages__item
          = link_to "#", class: "messages__item" do
            = image_tag 'logos/logo_red.svg', alt: 'logo_red', height: '48', width: '48'
            .messages__item__content
              .messages__item__content__text 佐藤さんからmacbookを購入
              .messages__item__content__date
                = icon("far", "clock")
                %span ２日前
            .messages__item__arrow
              = icon("fas", "chevron-right")

app/views/user_accounts/_mypage_sidebar.html.haml
.main__inner__sidebar
  %ul.main__inner__sidebar__menu
    %li.main__inner__sidebar__menu__item
      = link_to "#", class: "active" do
        %span マイページ
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span お知らせ
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span やることリスト
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span いいね一覧
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to new_product_path do
        %span 出品する
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 出品した商品・出品中
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 出品した商品・取引中
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 出品した商品・売却済み
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 購入した商品・取引中
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 購入した商品・過去の取引
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span ニュース一覧
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span 評価一覧
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span ガイド
        = icon("fas", "chevron-right")
    %li.main__inner__sidebar__menu__item
      = link_to "#" do
        %span お問い合わせ
        = icon("fas", "chevron-right")
  .main__inner__sidebar__payment
    %h3.main__inner__sidebar__payment__title メルペイ
    %ul.main__inner__sidebar__payment__list
      %li.main__inner__sidebar__payment__list__item
        = link_to "#" do
          %span 売上・振込申請
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__payment__list__item
        = link_to "#" do
          %span ポイント
          = icon("fas", "chevron-right")
  .main__inner__sidebar__config
    %h3.main__inner__sidebar__config__title 設定
    %ul.main__inner__sidebar__config__list
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span プロフィール
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span 発送元・お届け先住所変更
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span 支払い方法
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span メール
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span 本人情報
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to "#" do
          %span 電話番号の確認
          = icon("fas", "chevron-right")
      %li.main__inner__sidebar__config__list__item
        = link_to logout_user_accounts_path do
          %span ログアウト
          = icon("fas", "chevron-right")

app/views/user_accounts/index.html.haml
= render "shared/header_navbar"
.mypage
  .breadcrumb-wrapper
    .breadcrumb-inner
      - breadcrumb :mypage
      = breadcrumbs separator: " &rsaquo; "
  .main
    .main__inner
      = render "mypage_sidebar"
      = render "mypage_body"
= render "shared/footer"

app/views/user_accounts/logout.html.haml
%header
  = render "shared/header_navbar"
  .mypage
    .breadcrumb-wrapper
      .breadcrumb-inner
        - breadcrumb :logout
        = breadcrumbs separator: " &rsaquo; "
    .main
      .main__inner
        = render "user_accounts/mypage_sidebar"
        = render "tops/logoutpage"
%footer
  = render "shared/footer"
  = render partial: "tops/exibit_button"