config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :userprofile, only: [:index]
  resources :cwavetests, only: [:index, :create, :new]
  resources :user_accounts, only: [:index], path: "/mypage" do
    collection do
      get :logout
    end
  end
  resources :card_registrations, only: [:index, :new], path: "/mypage/card"
  resources :signup, only: [:new, :create] do
    collection do
      get :step1
      get :step2
      get :step3
      get :step4
    end
  end
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'js' }
      get 'get_category_grandchildren', defaults: { format: 'js' }
    end
    resources :purchases, only: [:index] do
      collection do
        post :pay
      end
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  # 購入画面はログインユーザーのみに表示
  before_action :authenticate_user!
  before_action :set_product, only: [:index, :pay]
  before_action :redirect_if_already_bought, only: [:index, :pay]

  def index
    @PAYJP_PUBLIC_KEY = ENV['PAYJP_PUBLIC_KEY']
  end

  def pay
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    begin
      charge = Payjp::Charge.create(
        amount: @product.price, # 決済する値段
        card: params['payjp-token'],
        currency: 'jpy'
      )
      @product.buy_product(current_user.user_profile)
      redirect_to root_path, notice: "購入しました"
    rescue Payjp::CardError => e
      redirect_with_flash("カードが無効であるか支払額が限度を超えています")
    rescue Payjp::InvalidRequestError => e
      redirect_with_flash("入力に間違いがあります")
    rescue Payjp::AuthenticationError => e
      redirect_with_flash("認証に失敗しました")
    rescue Payjp::APIConnectionError => e
      redirect_with_flash("通信に失敗しました")
    rescue Payjp::PayjpError => e
      redirect_with_flash("決済に失敗しました。窓口に問い合わせてください。")
    rescue => e
      redirect_with_flash("決済に失敗しました。窓口に問い合わせてください。")
    end
  end

  def redirect_with_flash(alert_message)
    flash[:payment_alert] = alert_message
    redirect_to product_purchases_path(params[:product_id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def redirect_if_already_bought
    if @product.bought_product.present? || @product.saling_product.blank?
      flash[:payment_alert] = "既に商品は品切れになっています。"
      redirect_to product_path(params[:product_id])
    end
  end
end

app/views/purchases/index.html.haml
= render partial: "shared/product_flash"
.exhibit-top
  =render 'single/single-header'

.exhibit

  %main.main
    %section.main__container.product-container
      .sell-upload-box
        .sell-container
          %h2.sell-container-head__confirm
            購入内容の確認
      %div.sell-all-contents

        .sell-content__confirm
          .product-detail
            .thumbnail__container
              %div.img__thumbnail
                - if @product.product_images.present?
                  = image_tag @product.product_images.first.image.to_s, alt: @product.name
              %h3.confirm__thumbnail
                = @product.name
            %p.buy__price
              %span.item__price
                = number_to_currency(@product.price, unit: "￥", precision: 0)
              %span.item__caption
                送料込み
            .have__you__point
              %strong ポイントはありません
            %p.buy__price__result
              支払い金額
              %span.item__price
                = number_to_currency(@product.price, unit: "￥", precision: 0)
            %p.buy__error
              この商品はアプリからのみ購入できます。
            -# .item__buying
            -# 購入する
            = form_with url: pay_product_purchases_path, method: :post, class: "payjp-form" do
              %script{ type:"text/javascript",
                src: "https://checkout.pay.jp",
                class: "payjp-button ",
                "data-text": "購入する",
                "data-key": @PAYJP_PUBLIC_KEY}
            %p.Proposal アプリをお持ちでない方は以下よりインストールしてご利用いただけます。
            .store__banners
              = link_to do
                ""
              = link_to do
                ""

        .sell-content__confirm
          .product-detail
            %h3.confirm__title 配送先
            .user__address 〒-
            %p.user__info
              = link_to do
                変更する >

        .sell-content__confirm
          .product-detail
            %h3.confirm__title 支払い方法
            .user__address /
            %p.user__info
              = link_to do
                変更する >

.exhibit-bottom
  =render 'single/single-footer'