config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :userprofile, only: [:index]
  resources :cwavetests, only: [:index, :create, :new]
  resources :user_accounts, only: [:index], path: "/mypage" do
    collection do
      get :logout
    end
  end
  resources :card_registrations, only: [:index, :new], path: "/mypage/card"
  resources :signup, only: [:new, :create] do
    collection do
      get :step1
      get :step2
      get :step3
      get :step4
    end
  end
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'js' }
      get 'get_category_grandchildren', defaults: { format: 'js' }
    end
    resources :purchases, only: [:index] do
      collection do
        post :pay
      end
    end
  end
end

app/models/address.rb
class Address < ActiveHash::Base
  
  self.data = [
    {id: 0, name: '--'},{id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bought_product.rb
class BoughtProduct < ApplicationRecord
  validates :product_id, uniqueness: true
  belongs_to :product
  belongs_to :user_profile
  belongs_to :buyer, class_name: "UserProfile"
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user_profile
  belongs_to :product
end

app/models/cwavetest.rb
class Cwavetest < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { name: "北海道", id: 1 },
    { name: "青森県", id: 2 },
    { name: "岩手県", id: 3 },
    { name: "宮城県", id: 4 },
    { name: "秋田県", id: 5 },
    { name: "山形県", id: 6 },
    { name: "福島県", id: 7 },
    { name: "茨城県", id: 8 },
    { name: "栃木県", id: 9 },
    { name: "群馬県", id: 10 },
    { name: "埼玉県", id: 11 },
    { name: "千葉県", id: 12 },
    { name: "東京都", id: 13 },
    { name: "神奈川県", id: 14 },
    { name: "新潟県", id: 15 },
    { name: "富山県", id: 16 },
    { name: "石川県", id: 17 },
    { name: "福井県", id: 18 },
    { name: "山梨県", id: 19 },
    { name: "長野県", id: 20 },
    { name: "岐阜県", id: 21 },
    { name: "静岡県", id: 22 },
    { name: "愛知県", id: 23 },
    { name: "三重県", id: 24 },
    { name: "滋賀県", id: 25 },
    { name: "京都府", id: 26 },
    { name: "大阪府", id: 27 },
    { name: "兵庫県", id: 28 },
    { name: "奈良県", id: 29 },
    { name: "和歌山県", id: 30 },
    { name: "鳥取県", id: 31 },
    { name: "島根県", id: 32 },
    { name: "岡山県", id: 33 },
    { name: "広島県", id: 34 },
    { name: "山口県", id: 35 },
    { name: "徳島県", id: 36 },
    { name: "香川県", id: 37 },
    { name: "愛媛県", id: 38 },
    { name: "高知県", id: 39 },
    { name: "福岡県", id: 40 },
    { name: "佐賀県", id: 41 },
    { name: "長崎県", id: 42 },
    { name: "熊本県", id: 43 },
    { name: "大分県", id: 44 },
    { name: "宮崎県", id: 45 },
    { name: "鹿児島県", id: 46 },
    { name: "沖縄県", id: 47 }
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  after_create :create_saling_product

  with_options presence: true do
    validates :name
    validates :description
    validates :status
    validates :who_charge_shipping
    validates :way_of_shipping
    validates :shipping_region
    validates :how_long_shipping
    validates :price
  end

  enum status: {
    "新品、未使用": 0,
    "未使用に近い": 1,
    "目立った汚れや傷なし": 2,
    "やや汚れや傷あり": 3,
    "傷や汚れあり": 4,
    "全体的に状態が悪い": 5
  }

  enum who_charge_shipping: {
    "送料込み（出品者負担）": 0, "着払い（購入者負担）": 1
  }

  enum way_of_shipping: {
    "未定": 0, "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3,
    "普通郵便（定型、定型外）": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8
  }

  enum how_long_shipping: {
    "1-2日で発送": 0, "2-3日で発送": 1, "4-7日で発送": 2
  }

  belongs_to :user_profile
  belongs_to :category
  has_one :saling_product, dependent: :destroy
  has_one :bought_product, dependent: :destroy
  has_one :sold_product, dependent: :destroy
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images

  has_many :comments, dependent: :destroy
  # 購入したuser(buyer)を取得
  has_one :buyer, through: :bought_product, source: :buyer
  # 受け取ったuser(buyer)を取得
  has_one :accepter, through: :sold_product, source: :buyer

  def create_saling_product
    SalingProduct.create(user_profile_id: user_profile.id, product_id: id)
  end

  def buy_product(buyer)
    if buyer.instance_of?(User)
      buyer = buyer.user_profile
    end
    BoughtProduct.create(user_profile_id: user_profile.id, product_id: id, buyer_id: buyer.id)
    saling_product.destroy
  end

  def sell_out_product
    SoldProduct.create(user_profile_id: user_profile.id, product_id: id, buyer_id: buyer.id)
    bought_product.destroy
  end

  def humanize_shipping_region
    Prefecture.find(shipping_region).name
  end

  def self.filter_by_category(category_name)
    products = Product.all
    filtered = products.select { |p| p.category.root.name == category_name }
    filtered.take(10)
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product
  #dependent: :destroyを入れてみようかどうか
end

app/models/saling_product.rb
class SalingProduct < ApplicationRecord
  validates :product_id, uniqueness: true
  belongs_to :product
  belongs_to :user_profile
end

app/models/sold_product.rb
class SoldProduct < ApplicationRecord
  validates :product_id, uniqueness: true
  belongs_to :product
  belongs_to :user_profile
  belongs_to :buyer, class_name: "UserProfile"
end

app/models/top.rb
class Top < ApplicationRecord
  has_many :product
  has_many :product_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :user_profile
  has_one :user_address
  with_options presence: true do
  validates :first_name
    validates :last_name
    validates :first_name_kana
    validates :last_name_kana
    validates :birth_day
    validates :phone_number
  end
  #ユーザー登録時に複数のテーブルに保存できるように親=>子へネストさせる
  accepts_nested_attributes_for :user_profile
  accepts_nested_attributes_for :user_address
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  validates :nickname, presence: true
  belongs_to :user
  has_one :user_address
  has_many :products
  has_many :comments, dependent: :destroy
  has_many :saling_products
  has_many :bought_products
  has_many :sold_products
  # 中間テーブル経由でproductsを取得
  has_many :salings, through: :saling_products, source: :product
  has_many :boughts, through: :bought_products, source: :product
  has_many :solds, through: :sold_products, source: :product
  # buyerが購入したproductsをbought_products経由で取得
  has_many :buying_products, class_name: "BoughtProduct", foreign_key: "buyer_id"
  has_many :buyings, through: :buying_products, source: :product
  # buyerが購入済みのproductssold_products経由でを取得
  has_many :accepted_products, class_name: "SoldProduct", foreign_key: "buyer_id"
  has_many :accepts, through: :accepted_products, source: :product
end

app/helpers/cwavetests_helper.rb
module CwavetestsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/tets_helper.rb
module TetsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/shared/_footer.html.haml
.banner
  .banner__inner
    .banner__inner__promotion
      %h2.banner__inner__promotion__title スマホでかんたんフリマアプリ
      %h2.banner__inner__promotion__text 今すぐ無料ダウンロード！
      .banner__inner__promotion__icons
        .banner__inner__promotion__icons__logo
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', width: "58", height: "58"
        %ul.banner__inner__promotion__icons__apps
          %li.banner__inner__promotion__icons__apps__item
            = link_to "#" do
              = image_tag 'badges/App_Store_Badge.svg', alt: 'App_Store_Badge', width: "133", height: "40"
          %li.banner__inner__promotion__icons__apps__item
            = link_to "#" do
              = image_tag 'badges/google-play-badge.png', alt: 'google-play-badge', width: "133", height: "40"
    .banner__inner__image
      = image_tag 'logos/logo_red.svg', alt: 'logo_gray', width: "68", width: "260", height: "260"
.footer
  .footer__nav
    .footer__nav__cell
      %h2.footer__nav__cell__title メルカリについて
      %ul.footer__nav__cell__menu
        %li.footer__nav__cell__menu__item
          =link_to "会社概要（運営会社）", "#"
        %li.footer__nav__cell__menu__item
          =link_to "採用情報", "#"
        %li.footer__nav__cell__menu__item
          =link_to "プレスリリース", "#"
        %li.footer__nav__cell__menu__item
          =link_to "公式ブログ", "#"
        %li.footer__nav__cell__menu__item
          =link_to "メルカリロゴ利用ガイドライン", "#"
        %li.footer__nav__cell__menu__item
          %ul.footer__nav__cell__menu__item__social
            %li
              =link_to "#" do
                = icon("fab", "twitter")
            %li
              =link_to "#" do
                = icon("fab", "facebook-square")
    .footer__nav__cell
      %h2.footer__nav__cell__title ヘルプ＆ガイド
      %ul.footer__nav__cell__menu
        %li.footer__nav__cell__menu__item
          =link_to "メルカリガイド", "#"
        %li.footer__nav__cell__menu__item
          =link_to "らくらくメルカリ便", "#"
        %li.footer__nav__cell__menu__item
          =link_to "ゆうゆうメルカリ便", "#"
        %li.footer__nav__cell__menu__item
          =link_to "大型メルカリ便", "#"
        %li.footer__nav__cell__menu__item
          =link_to "車体取引ガイド", "#"
        %li.footer__nav__cell__menu__item
          =link_to "メルカリあんしん・あんぜん宣言！", "#"
        %li.footer__nav__cell__menu__item
          =link_to "偽ブランド品撲滅への取り組み", "#"
        %li.footer__nav__cell__menu__item
          =link_to "メルカリボックス", "#"
    .footer__nav__cell.two-columns
      %h2.footer__nav__cell__title プライバシーと利用規約
      .footer__nav__cell__inner
        %ul.footer__nav__cell__menu
          %li.footer__nav__cell__menu__item
            =link_to "プライバシーポリシー", "#"
          %li.footer__nav__cell__menu__item
            =link_to "メルカリ利用規約", "#"
          %li.footer__nav__cell__menu__item
            =link_to "あんしんスマホサポート制度に関する利用特約", "#"
          %li.footer__nav__cell__menu__item
            =link_to "コンプライアンスポリシー", "#"
        %ul.footer__nav__cell__menu
          %li.footer__nav__cell__menu__item
            =link_to "個人データの安全管理に係る基本方針", "#"
          %li.footer__nav__cell__menu__item
            =link_to "特定商取引に関する表記", "#"
          %li.footer__nav__cell__menu__item
            =link_to "資金決済法に基づく表示", "#"
          %li.footer__nav__cell__menu__item
            =link_to "法令順守と犯罪抑止のために", "#"
    .footer__nav__cell
      %h2.footer__nav__cell__title 国
      %ul.footer__nav__cell__menu
        %li.footer__nav__cell__menu__item
          =link_to "日本", "#"
        %li.footer__nav__cell__menu__item
          =link_to "United States", "#"
  .footer__bottom
    = link_to "#", class: "footer__bottom__logo" do
      = image_tag 'logos/fmarket_logo_custom_white.svg', alt: 'fmarket_logo_custom_white', height: '33', width: '124', style: "fill: white"
    .footer__bottom__copyright
      %span &copy; 2019 Mercari

app/views/shared/_footer_img_only.html.haml
.banner
  .banner__inner
    .banner__inner__promotion
      %h2.banner__inner__promotion__title スマホでかんたんフリマアプリ
      %h2.banner__inner__promotion__text 今すぐ無料ダウンロード！
      .banner__inner__promotion__icons
        .banner__inner__promotion__icons__logo
          = image_tag 'logos/logo_red.svg', alt: 'logo_red', width: "58", height: "58"
        %ul.banner__inner__promotion__icons__apps
          %li.banner__inner__promotion__icons__apps__item
            = link_to "#" do
              = image_tag 'badges/App_Store_Badge.svg', alt: 'App_Store_Badge', width: "133", height: "40"
          %li.banner__inner__promotion__icons__apps__item
            = link_to "#" do
              = image_tag 'badges/google-play-badge.png', alt: 'google-play-badge', width: "133", height: "40"
    .banner__inner__image
      = image_tag 'logos/logo_red.svg', alt: 'logo_gray', width: "68", width: "260", height: "260"

app/views/shared/_header_navbar.html.haml
.pc-header
  .pc-header__inner
    .pc-header__inner__top
      = link_to root_path, class: "pc-header__inner__top__logo" do
        = image_tag 'logos/fmarket_logo_red.svg', alt: 'fmarket_logo', height: '36', width: '134'
      %form.pc-header__inner__top__search
        %input{ type: "search", placeholder: "何かお探しですか？", class: "pc-header__inner__top__search__input" }
        .pc-header__inner__top__search__icon
          = icon("fas", "search", class: "pc-header__inner__top__search__icon")
    .pc-header__inner__navbar
      %ul.pc-header__inner__navbar__menu-left
        %li.pc-header__inner__navbar__menu-left__item
          = link_to "#" do
            = icon("fas" , "list")
            %span カテゴリーから探す
        %li.pc-header__inner__navbar__menu-left__item
          = link_to "#" do
            = icon("fas", "tags")
            %span ブランドから探す
      %ul.pc-header__inner__navbar__menu-right
        %li.pc-header__inner__navbar__menu-right__item
          = link_to "#" do
            = icon("far", "heart")
            %span いいね！一覧
        %li.pc-header__inner__navbar__menu-right__item
          = link_to "#" do
            = icon("far", "bell")
            %span お知らせ
        %li.pc-header__inner__navbar__menu-right__item
          = link_to "#" do
            = icon("fas", "check")
            %span やることリスト
        %li.pc-header__inner__navbar__menu-right__item
          - if user_signed_in?
            = link_to user_accounts_path do
              = image_tag 'mypage/boy_01.png', alt: 'user_icon', height: '32', width: '32'
              %span #{current_user.user_profile.nickname}
          - else
            = link_to "ログイン", new_user_session_path
        %li.pc-header__inner__navbar__menu-right__item
          - unless user_signed_in?
            = link_to "新規会員登録", step1_signup_index_path

app/views/shared/_product_flash.html.haml
.flash
  - flash.each do |key, value|
    - if key == "payment_alert"
      = content_tag(:div, value, class: "flash__message--alert")
    - if key == "exhibit_notice"
      = content_tag(:div, value, class: "flash__message--notice")
  - if flash.keys.include?("exhibit_errors")
    - flash[:exhibit_errors].each do |key, values|
      - values.each do |value|
        = content_tag(:div, "#{key}: #{value}", class: "flash__message--notice")

app/views/shared/_registration_header.html.haml
.registration__page__header__wrapper  
  .registration__page__header
    = link_to "", class: "" do
      = image_tag 'logos/fmarket_logo_red.svg', alt: 'fmarket_logo', height: '55'
    .phased__caption__and__registration
      %ul.phased__caption
        %li.phased__caption__one
          会員情報
        %li.phased__caption__two
          電話番号認証
        %li.phased__caption__three
          お届け先情報入力
        %li.phased__caption__four
          支払い方法
        %li.phased__caption__five
          完了
      .phased__registration
        .circle__check__object--red
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray

app/views/shared/_registration_header__two.html.haml
.registration__page__header__wrapper  
  .registration__page__header
    = link_to "", class: "" do
      = image_tag 'logos/fmarket_logo_red.svg', alt: 'fmarket_logo', height: '55'
    .phased__caption__and__registration
      %ul.phased__caption
        %li.phased__caption__one
          会員情報
        %li.phased__caption__two
          電話番号認証
        %li.phased__caption__three
          お届け先情報入力
        %li.phased__caption__four
          支払い方法
        %li.phased__caption__five
          完了
      .phased__registration
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray

app/views/shared/_registration_header_five.html.haml
.registration__page__header__wrapper  
  .registration__page__header
    = link_to "", class: "" do
      = image_tag 'logos/fmarket_logo_red.svg', alt: 'fmarket_logo', height: '55'
    .phased__caption__and__registration
      %ul.phased__caption
        %li.phased__caption__one
          会員情報
        %li.phased__caption__two
          電話番号認証
        %li.phased__caption__three
          お届け先情報入力
        %li.phased__caption__four
          支払い方法
        %li.phased__caption__five
          完了
      .phased__registration
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red

app/views/shared/_registration_header_three.html.haml
.registration__page__header__wrapper  
  .registration__page__header
    = link_to "", class: "" do
      = image_tag 'logos/fmarket_logo_red.svg', alt: 'fmarket_logo', height: '55'
    .phased__caption__and__registration
      %ul.phased__caption
        %li.phased__caption__one
          会員情報
        %li.phased__caption__two
          電話番号認証
        %li.phased__caption__three
          お届け先情報入力
        %li.phased__caption__four
          支払い方法
        %li.phased__caption__five
          完了
      .phased__registration
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--red
        .circle__check__object--red
        .line__check__object--gray
        .circle__check__object--gray
        .line__check__object--gray
        .circle__check__object--gray

app/views/single/_single-footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix.footer-contract
      %li
        .li-privacy
          = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li
        .li-contract
          = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
      %li
        .li-transaction
          = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
  .single-footer__logo
    %figure.single-footer__logo-img
      = image_tag("logo_gray.svg")
  %p
    %small © 2019 Mercari

app/views/single/_single-header.html.haml
%header.single-header
  %h1
    %figure.single-header__icon
      %figure.single-header__icon-image
        = link_to root_path do
          = image_tag("fmarket_logo_red.svg")

app/views/user_registration_comp_of_regi/new.html.haml
= render "shared/registration_header_five"
.registration__page__wrapper
  .registration__page__wrapper__container
    %h2.registration__page__wrapper__container__page__title
      会員登録完了
    .registration__page__wrapper__container__form__group
      %p.registration__text.t-center
        ありがとうございます
        %br
        会員登録が完了しました。
      = link_to "", class: "registration__push__next cmb" do
        サービスを始める
    = render "shared/footer_img_only"

app/views/user_registration_one/new.html.haml
.exhibit-top
  =render 'single/single-header'
.exhibit
  %main.main
    .registration__container
      %h2.registration__container__title
        新規会員登録
      .registration__container__contents
        = link_to "", class: "btn__mail" do
          メールアドレスで登録する
        = link_to "", class: "btn__facebook" do
          facebookで登録する
        = link_to "", class: "btn__google" do
          Googleアドレスで登録する
.exhibit__bottom
  =render 'single/single-footer'

app/views/user_registration_seven/_registration_finish.html.haml
.main__inner__body
  .registration__finish__container
    %h2.registration__finish__container__title
      確認完了
    .registration__finish__container__information
      %p.registration__finish__caption
        メルカリをご利用いただき誠にありがとうございます。
        %br
        ○○○○○@gmail.comの確認が完了しました。
        %br
        引き続き当サービスをお楽しみください。

app/views/user_registration_seven/new.html.haml
%header
  = render "shared/header_navbar"
  .mypage
    .breadcrumb-wrapper
      .breadcrumb-inner
        - breadcrumb :registrationfinish
        = breadcrumbs separator: " &rsaquo; "
    .main
      .main__inner
        = render "user_accounts/mypage_sidebar"
        = render "user_registration_seven/registration_finish"
%footer
  = render "shared/footer"
  = render "tops/exibit_button"