config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tops#index"
  resources :userprofile, only: [:index]
  resources :cwavetests, only: [:index, :create, :new]
  resources :user_accounts, only: [:index], path: "/mypage" do
    collection do
      get :logout
    end
  end
  resources :card_registrations, only: [:index, :new], path: "/mypage/card"
  resources :signup, only: [:new, :create] do
    collection do
      get :step1
      get :step2
      get :step3
      get :step4
    end
  end
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'js' }
      get 'get_category_grandchildren', defaults: { format: 'js' }
    end
    resources :purchases, only: [:index] do
      collection do
        post :pay
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  after_create :create_saling_product

  with_options presence: true do
    validates :name
    validates :description
    validates :status
    validates :who_charge_shipping
    validates :way_of_shipping
    validates :shipping_region
    validates :how_long_shipping
    validates :price
  end

  enum status: {
    "新品、未使用": 0,
    "未使用に近い": 1,
    "目立った汚れや傷なし": 2,
    "やや汚れや傷あり": 3,
    "傷や汚れあり": 4,
    "全体的に状態が悪い": 5
  }

  enum who_charge_shipping: {
    "送料込み（出品者負担）": 0, "着払い（購入者負担）": 1
  }

  enum way_of_shipping: {
    "未定": 0, "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3,
    "普通郵便（定型、定型外）": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8
  }

  enum how_long_shipping: {
    "1-2日で発送": 0, "2-3日で発送": 1, "4-7日で発送": 2
  }

  belongs_to :user_profile
  belongs_to :category
  has_one :saling_product, dependent: :destroy
  has_one :bought_product, dependent: :destroy
  has_one :sold_product, dependent: :destroy
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images

  has_many :comments, dependent: :destroy
  # 購入したuser(buyer)を取得
  has_one :buyer, through: :bought_product, source: :buyer
  # 受け取ったuser(buyer)を取得
  has_one :accepter, through: :sold_product, source: :buyer

  def create_saling_product
    SalingProduct.create(user_profile_id: user_profile.id, product_id: id)
  end

  def buy_product(buyer)
    if buyer.instance_of?(User)
      buyer = buyer.user_profile
    end
    BoughtProduct.create(user_profile_id: user_profile.id, product_id: id, buyer_id: buyer.id)
    saling_product.destroy
  end

  def sell_out_product
    SoldProduct.create(user_profile_id: user_profile.id, product_id: id, buyer_id: buyer.id)
    bought_product.destroy
  end

  def humanize_shipping_region
    Prefecture.find(shipping_region).name
  end

  def self.filter_by_category(category_name)
    products = Product.all
    filtered = products.select { |p| p.category.root.name == category_name }
    filtered.take(10)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :category_select_function, only: [:new, :edit]
  before_action :set_existing_product, only: [:show, :edit, :update]

  def show
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    unless extract_product_images.size > 0
      flash[:exhibit_notice] = "画像は１枚以上必要です"
      redirect_to new_product_path and return
    end

    if @product.save
      extract_product_images.each do |image|
        @product.product_images.create(image: image, product_id: @product.id)
      end
      flash[:exhibit_notice] = "出品しました"
      redirect_to product_path(@product.id)
    else
      flash[:exhibit_notice] = "未入力の項目があります"
      redirect_to new_product_path
    end
  end

  def edit
    category_path = @product.category.path
    @category_root = category_path[0]
    @category_child = category_path[1]
    @category_grandchild = category_path[2]
  end

  def update
    unless (extract_existing_product_images.size + extract_product_images.size) > 0
      flash[:exhibit_notice] = "画像は１枚以上必要です"
      redirect_to edit_product_path(params[:id]) and return
    end
    if @product.update(product_params)
      remove_product_images
      extract_product_images.each do |image|
        @product.product_images.create(image: image, product_id: @product.id)
      end
      flash[:exhibit_notice] = "編集しました"
      redirect_to product_path(params[:id])
    else
      flash[:exhibit_notice] = "未入力の項目があります"
      redirect_to edit_product_path(params[:id])
    end
  end

  #カテゴリー選択機能
  def category_select_function
    @category_parent_array = [{ name: "---", id: "" }]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << { name: parent.name, id: parent.id }
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    @category_array = []
    category_children = Category.find(params[:category_id]).children
    category_children.each do |child|
      @category_array << { name: child.name, id: child.id }
    end
    respond_to do |format|
      format.js do
        @status = "success"
        @name = "category_child"
      end
    end
  end

  def get_category_grandchildren
    @category_array = []
    category_grandchildren = Category.find(params[:child_id]).children
    category_grandchildren.each do |child|
      @category_array << { name: child.name, id: child.id }
    end

    respond_to do |format|
      format.js do
        @status = "success"
        @name = "category_grandchild"
      end
    end
  end

  def destroy
    product = Product.find(params[:id])
    if product.destroy
      redirect_to root_path
    else
      redirect_to product_path(params[:id])
    end
  end

  private

  def set_existing_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name, :description, :status,
      :who_charge_shipping, :way_of_shipping, :shipping_region,
      :how_long_shipping, :price, :brand
    ).merge(
      category_id: product_category_param,
      user_profile_id: current_user.user_profile.id
    )
  end

  def product_category_param
    category_params = params.require(:product).permit(:category, :category_child, :category_grandchild)
    category_params[:category_grandchild] || category_params[:category_child] || category_params[:category]
  end

  def product_image_param
    params.require(:product)["product_images_attributes"] || []
  end

  def extract_product_images
    images_array = []
    product_image_param.each do |index, image|
      if image[:image]
        images_array << image[:image][0]
      end
    end
    images_array
  end

  def extract_existing_product_images
    images_ids_array = []
    product_image_param.each do |index, image|
      if image[:id]
        images_ids_array << image[:id].to_i
      end
    end
    images_ids_array
  end

  def remove_product_images
    @product.product_image_ids.each do |i|
      unless extract_existing_product_images.include?(i)
        @product.product_images.destroy(i)
      end
    end
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_edit_product_category.html.haml
%ul.exhibit-center__main__form-section__group-list
  %li.exhibit-center__main__form-section__group__form--select
    = f.select :category, options_for_select(@category_parent_array.map{ |c| [c[:name], c[:id]] }, selected: @product.category.root.id)
    = icon("fas", "chevron-down")
  %li.exhibit-center__main__form-section__group__form--select#select_category_child
    = f.select :category_child, options_for_select(@category_root.children.map{ |c| [c[:name], c[:id]] }, selected: @category_child ? @category_child.id : false)
    = icon("fas", "chevron-down")
  - if @category_child
    %li.exhibit-center__main__form-section__group__form--select#select_category_grandchild
      = f.select :category_grandchild, options_for_select(@category_child.children.map{ |c| [c[:name], c[:id]] }, selected: @category_grandchild ? @category_grandchild.id : false)
      = icon("fas", "chevron-down")

app/views/products/_new_product_category.html.haml
%ul.exhibit-center__main__form-section__group-list
  %li.exhibit-center__main__form-section__group__form--select
    = f.select :category, options_for_select(@category_parent_array.map{ |c| [c[:name], c[:id]] })
    = icon("fas", "chevron-down")

app/views/products/_product_category_select.html.erb
<li class="exhibit-center__main__form-section__group__form--select" id="select_<%= @name %>">
  <%= select_tag "product[#{@name}]",
    options_for_select(category_array.map{ |c| [c[:name], c[:id]] }),
    id: "product_#{@name}" %>
  <%= icon("fas", "chevron-down") %>
</li>

app/views/products/_product_detail_thumbnail.html.haml
%li= image_tag img.image.to_s, alt: @product.name, height: height, width: width

app/views/products/_product_exhibit_form.html.haml
= form_with(model: @product, url: url, local: true, class: "exhibit-center__main") do |f|
  %h2.exhibit-center__main__title 商品の情報を入力
  %section.exhibit-center__main__form-section
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label "出品画像"
        %span 必須
      %p.exhibit-center__main__form-section__group__text 最大5枚までアップロードできます
    .exhibit-center__main__form-section__images
      %ul.exhibit-center__main__form-section__images__preview
        - unless @product.new_record?
          = render partial: "product_images_preview_item", collection: @product.product_images.limit(5), as: :image
      .exhibit-center__main__form-section__images__residue
        - if @product.new_record?
          = render partial: "product_images_new_fields", locals: { f: f }
        - else
          = render partial: "product_images_edit_fields", locals: { f: f }
  %section.exhibit-center__main__form-section
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :name, "商品名"
        %span 必須
      .exhibit-center__main__form-section__group__form
        = f.text_field :name, placeholder: "商品の名前（必須、４０文字以内）", maxlength: "40", class: "exhibit-center__main__form-section__group__form__input"
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :description, "商品の説明"
        %span 必須
      .exhibit-center__main__form-section__group__form
        = f.text_area :description, rows: 4, placeholder: "商品の説明（必須、１０００文字以内）", class: "exhibit-center__main__form-section__group__form__textarea"
  %section.exhibit-center__main__form-section
    %h3.exhibit-center__main__form-section__title 商品の詳細
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :category, "カテゴリー"
        %span 必須
      - if @product.new_record?
        = render partial: "new_product_category", locals: { f: f }
      - else
        = render partial: "edit_product_category", locals: { f: f }
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :brand, "ブランド"
        %span 必須
      .exhibit-center__main__form-section__group__form
        = f.text_field :brand, placeholder: "例）シャネル", maxlength: "40", class: "exhibit-center__main__form-section__group__form__input"
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :status, "商品の状態"
        %span 必須
      .exhibit-center__main__form-section__group__form--select
        = f.select :status, Product.statuses.keys.to_a, { prompt: '---' }
        = icon("fas", "chevron-down")
  %section.exhibit-center__main__form-section
    %h3.exhibit-center__main__form-section__title 配送について
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :who_charge_shipping, "配送料の負担"
        %span 必須
      .exhibit-center__main__form-section__group__form--select
        = f.select :who_charge_shipping, Product.who_charge_shippings.keys.to_a, { prompt: '---' }
        = icon("fas", "chevron-down")
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :way_of_shipping, "配送の方法"
        %span 必須
      .exhibit-center__main__form-section__group__form--select
        = f.select :way_of_shipping, Product.way_of_shippings.keys.to_a, { prompt: '---' }
        = icon("fas", "chevron-down")
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :shipping_region, "発送元の地域"
        %span 必須
      .exhibit-center__main__form-section__group__form--select
        = f.collection_select :shipping_region, Prefecture.all, :id, :name, { prompt: '---' }
        = icon("fas", "chevron-down")
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :how_long_shipping, "発送までの日数"
        %span 必須
      .exhibit-center__main__form-section__group__form--select
        = f.select :how_long_shipping, Product.how_long_shippings.keys.to_a, { prompt: '---' }
        = icon("fas", "chevron-down")
  %section.exhibit-center__main__form-section
    %h3.exhibit-center__main__form-section__title 販売価格(300〜9,999,999)
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__title
        = f.label :price, "価格"
        %span 必須
      .exhibit-center__main__form-section__group__form
        = f.text_field :price, placeholder: "例）300", class: "exhibit-center__main__form-section__group__form__input"
    .exhibit-center__main__form-section__calculate
      .exhibit-center__main__form-section__calculate__text 販売手数料 (10%)
      .exhibit-center__main__form-section__calculate__result--fee
        %span ---
    .exhibit-center__main__form-section__calculate
      .exhibit-center__main__form-section__calculate__text 販売利益
      .exhibit-center__main__form-section__calculate__result--profit
        %span ---
  %section.exhibit-center__main__form-section
    .exhibit-center__main__form-section__explanation
      %p 禁止されている出品、行為を必ずご確認ください。
      %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
      %p また、出品をもちまして加盟店規約に同意したことになります。
    .exhibit-center__main__form-section__group
      .exhibit-center__main__form-section__group__form
        = f.submit value: "#{ (@product.new_record?) ? "出品する" : "変更する"}", class: "exhibit-center__main__form-section__group__form__button--submit"
        = link_to "#", class: "exhibit-center__main__form-section__group__form__button--cancel" do
          %span 戻る

app/views/products/_product_images_edit_fields.html.haml
= file_field_tag "product[product_images_attributes][#{@product.product_image_ids.max + 1}][image][]",
    id: "product_product_images_attributes_#{@product.product_image_ids.max + 1}_image",
    class: "exhibit-center__main__form-section__images__residue__input",
    multiple: true,
    data: {"image-id": @product.product_image_ids.max + 1}
= label_tag "product_product_images_attributes_#{@product.product_image_ids.max + 1}_image" do
  .exhibit-center__main__form-section__images__residue__icon
    = icon("fas", "camera")
  .exhibit-center__main__form-section__images__residue__text クリックしてアップロード
= f.fields_for :product_images do |image|
  = image.file_field :image, multiple: true, data: {"image-id": image.object.id}

app/views/products/_product_images_new_fields.html.haml
= f.fields_for :product_images do |image|
  = image.file_field :image, multiple: true, class: "exhibit-center__main__form-section__images__residue__input", data: {"image-id": 0}
  = image.label :image do
    .exhibit-center__main__form-section__images__residue__icon
      = icon("fas", "camera")
    .exhibit-center__main__form-section__images__residue__text クリックしてアップロード

app/views/products/_product_images_preview_item.html.haml
%li.exhibit-center__main__form-section__images__preview__item{ data: {"image-id": image.id} }
  .exhibit-center__main__form-section__images__preview__item__image
    = image_tag image.image_url, alt: image.image.identifier
  .exhibit-center__main__form-section__images__preview__item__button-delete
    %span 削除

app/views/products/edit.html.haml
= render "shared/product_flash"
.exhibit-top
  = render 'single/single-header'
.exhibit-center
  = render partial: "product_exhibit_form", locals: { url: product_path }
.exhibit-bottom
  = render 'single/single-footer'

app/views/products/get_category_children.js.erb
$(".exhibit-center__main__form-section__group-list").append("<%= j(render("product_category_select", category_array: @category_array)) %>");

app/views/products/get_category_grandchildren.js.erb
$(".exhibit-center__main__form-section__group-list").append("<%= j(render("product_category_select", category_array: @category_array)) %>");

app/views/products/new.html.haml
= render "shared/product_flash"
.exhibit-top
  = render 'single/single-header'
.exhibit-center
  = render partial: "product_exhibit_form", locals: { url: products_path }
.exhibit-bottom
  = render 'single/single-footer'

app/views/products/show.html.haml
= render "shared/product_flash"
= render "shared/header_navbar"
= render "product_detail"
= render "shared/footer"